name: Validate and Release

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.java'
      - '**.kt'
      - '**.xml'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: [ubuntu-latest]
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
          check-latest: false

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4

      - name: Run Tests
        id: run-tests
        run: mvn --batch-mode clean verify

      - name: Release
        if: github.
        uses: qcastel/github-actions-maven-release@master
        with:
          git-release-bot-name: "bot-idhub"
          git-release-bot-email: "bot@idhub.io"
          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -Dmaven.deploy.skip=true"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
