name: Push Validation

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.java'
      - '**.kt'
      - '**.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          check-latest: false

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4

      - name: Run Tests
        run: mvn -B clean verify
